### PR TITLE
Use LLVM 15

### LINKED ISSUE #226: Upgrade to LLVM 15
Newer versions of `rustc` use LLVM 15, which is why the CI is currently broken.

Needs support in `llvm-ir` first: https://github.com/cdisselkoen/llvm-ir/issues/24

### PR DESCRIPTION
**Pull request by woodruffw**
Closes #226.

~~None of this will work yet, since it's waiting on a release from `llvm-ir`.~~

### CODE REVIEW

**Comment by woodruffw** [comment]
Unblocked by upstream.

**Review by smoelius — APPROVED** [review]
LGTM.

I'm curious, though. Why did `tests/suffix_array_expected_badness.txt` have to change?

**Comment by woodruffw** [comment]
> I'm curious, though. Why did `tests/suffix_array_expected_badness.txt` have to change?

I didn't fully root-cause these, but my educated guess is that they changed due to changes in Rust itself -- my (maybe incorrect?) understanding is that Siderophile counts unsafety in the standard library as well, so changes to the stdlib would propagate to its callers.

**Comment by smoelius** [comment]
Gotcha. Thanks!

**Pull request merged**
