### PR TITLE
Update Cargo.toml to use LLVM-12

### PR DESCRIPTION
**Pull request by rennergade**
Minor update to use newer LLVM version

### CODE REVIEW

**Comment by woodruffw** [comment]
The CI also probably needs to be updated to install LLVM 12 instead. Would you mind doing that as well?

**Comment by rennergade** [comment]
Sure. I updated the versions. Is there a way to test this implicitly?

**Comment by smoelius** [comment]
> Sure. I updated the versions. Is there a way to test this implicitly?

I think the policy we should adopt is: the LLVM version to which `siderophile` is pinned should be the same as that of the latest stable rust.
```
$ rustc --version --verbose
rustc 1.54.0 (a178d0322 2021-07-26)
binary: rustc
commit-hash: a178d0322ce20e33eac124758e837cbd80a6f633
commit-date: 2021-07-26
host: x86_64-apple-darwin
release: 1.54.0
LLVM version: 12.0.1
              ^^^^^^
```
`siderophile` [insists on](https://github.com/trailofbits/siderophile/blob/797288fcba3c668154a1849aaba80755a3d9108f/src/utils.rs#L84-L97) using the default compiler. `siderophile` should check that the default compiler uses the LLVM version it expects. And, as a consequence, CI should fail when there is a mismatch.

I will open a separate issue for this, and we can continue the discussion there.

**Review by smoelius — APPROVED** [review]

**Comment by smoelius** [comment]
We will also have to update the README ([here](https://github.com/trailofbits/siderophile#installation)), but I can do that after we merge.

@woodruffw I am going to merge this and close #146 if this looks good to you.

**Comment by smoelius** [comment]
Thanks a lot, @rennergade.

**Pull request merged**
